// Generated by scripts/generate-work-contract.ts from Runtime-owned schemas.
// Do not edit this file directly.

export const WORK_API_VERSION = "1.0" as const;
export const WORK_SCHEMA_ID = "urn:aperture:work-event:1.0" as const;
export const WORK_BATCH_SCHEMA_ID = "urn:aperture:work-event-batch:1.0" as const;
export const WORK_SCHEMA_URL =
  "https://raw.githubusercontent.com/tomismeta/aperture/aperture-v0.5.0/schemas/work-event.schema.json";

export type WorkEvent =
  | {
      specVersion?: "1.0";
      id?: string;
      source?: string;
      type?: string;
      time?: string;
      subject?: string;
      schema?: string;
      contentType?: string;
      trace?: { traceparent?: string; tracestate?: string };
      run?: { sessionId?: string; runId?: string };
      kind: "work.started";
      work: {
        id: string;
        title?: string;
        summary?: string;
        reason?: string;
        progress?: number;
        status?: "running" | "waiting" | "blocked" | "failed" | "completed" | "cancelled";
      };
      actor?: {
        id: string;
        kind?: "agent" | "subagent" | "host" | "system" | "human";
        label?: string;
      };
      facts?: { capabilityFamily?: string; activityCategory?: string };
      hints?: {
        consequence?: "low" | "medium" | "high";
        capabilityFamily?: string;
        activityCategory?: string;
        requestKind?: "approval" | "choice" | "form";
      };
      context?: { items?: Array<{ id: string; label?: string; value: string | number | boolean }> };
      automation?: {
        runMode?: "interactive" | "background" | "scheduled";
        trigger?: string;
        recurrence?: "once" | "recurring";
        scheduleId?: string;
      };
      execution?: { surface?: string; placement?: string; runner?: string; environment?: string };
      governance?: {
        policyId?: string;
        approvalState?: "not_required" | "pending" | "approved" | "rejected";
        approvalId?: string;
        decisionId?: string;
      };
      usage?: {
        model?: string;
        modelRouting?: string;
        inputTokens?: number;
        cachedInputTokens?: number;
        outputTokens?: number;
        costUsd?: number;
      };
      extensions?: Record<string, unknown>;
    }
  | {
      specVersion?: "1.0";
      id?: string;
      source?: string;
      type?: string;
      time?: string;
      subject?: string;
      schema?: string;
      contentType?: string;
      trace?: { traceparent?: string; tracestate?: string };
      run?: { sessionId?: string; runId?: string };
      kind: "work.updated";
      work: {
        id: string;
        title?: string;
        summary?: string;
        reason?: string;
        progress?: number;
        status: "running" | "waiting" | "blocked" | "failed" | "completed";
      };
      actor?: {
        id: string;
        kind?: "agent" | "subagent" | "host" | "system" | "human";
        label?: string;
      };
      facts?: { capabilityFamily?: string; activityCategory?: string };
      hints?: {
        consequence?: "low" | "medium" | "high";
        capabilityFamily?: string;
        activityCategory?: string;
        requestKind?: "approval" | "choice" | "form";
      };
      context?: { items?: Array<{ id: string; label?: string; value: string | number | boolean }> };
      automation?: {
        runMode?: "interactive" | "background" | "scheduled";
        trigger?: string;
        recurrence?: "once" | "recurring";
        scheduleId?: string;
      };
      execution?: { surface?: string; placement?: string; runner?: string; environment?: string };
      governance?: {
        policyId?: string;
        approvalState?: "not_required" | "pending" | "approved" | "rejected";
        approvalId?: string;
        decisionId?: string;
      };
      usage?: {
        model?: string;
        modelRouting?: string;
        inputTokens?: number;
        cachedInputTokens?: number;
        outputTokens?: number;
        costUsd?: number;
      };
      extensions?: Record<string, unknown>;
    }
  | {
      specVersion?: "1.0";
      id?: string;
      source?: string;
      type?: string;
      time?: string;
      subject?: string;
      schema?: string;
      contentType?: string;
      trace?: { traceparent?: string; tracestate?: string };
      run?: { sessionId?: string; runId?: string };
      kind: "work.completed";
      work: {
        id: string;
        title?: string;
        summary?: string;
        reason?: string;
        progress?: number;
        status?: "running" | "waiting" | "blocked" | "failed" | "completed" | "cancelled";
      };
      actor?: {
        id: string;
        kind?: "agent" | "subagent" | "host" | "system" | "human";
        label?: string;
      };
      facts?: { capabilityFamily?: string; activityCategory?: string };
      hints?: {
        consequence?: "low" | "medium" | "high";
        capabilityFamily?: string;
        activityCategory?: string;
        requestKind?: "approval" | "choice" | "form";
      };
      context?: { items?: Array<{ id: string; label?: string; value: string | number | boolean }> };
      automation?: {
        runMode?: "interactive" | "background" | "scheduled";
        trigger?: string;
        recurrence?: "once" | "recurring";
        scheduleId?: string;
      };
      execution?: { surface?: string; placement?: string; runner?: string; environment?: string };
      governance?: {
        policyId?: string;
        approvalState?: "not_required" | "pending" | "approved" | "rejected";
        approvalId?: string;
        decisionId?: string;
      };
      usage?: {
        model?: string;
        modelRouting?: string;
        inputTokens?: number;
        cachedInputTokens?: number;
        outputTokens?: number;
        costUsd?: number;
      };
      extensions?: Record<string, unknown>;
    }
  | {
      specVersion?: "1.0";
      id?: string;
      source?: string;
      type?: string;
      time?: string;
      subject?: string;
      schema?: string;
      contentType?: string;
      trace?: { traceparent?: string; tracestate?: string };
      run?: { sessionId?: string; runId?: string };
      kind: "work.cancelled";
      work: {
        id: string;
        title?: string;
        summary?: string;
        reason?: string;
        progress?: number;
        status?: "running" | "waiting" | "blocked" | "failed" | "completed" | "cancelled";
      };
      actor?: {
        id: string;
        kind?: "agent" | "subagent" | "host" | "system" | "human";
        label?: string;
      };
      facts?: { capabilityFamily?: string; activityCategory?: string };
      hints?: {
        consequence?: "low" | "medium" | "high";
        capabilityFamily?: string;
        activityCategory?: string;
        requestKind?: "approval" | "choice" | "form";
      };
      context?: { items?: Array<{ id: string; label?: string; value: string | number | boolean }> };
      automation?: {
        runMode?: "interactive" | "background" | "scheduled";
        trigger?: string;
        recurrence?: "once" | "recurring";
        scheduleId?: string;
      };
      execution?: { surface?: string; placement?: string; runner?: string; environment?: string };
      governance?: {
        policyId?: string;
        approvalState?: "not_required" | "pending" | "approved" | "rejected";
        approvalId?: string;
        decisionId?: string;
      };
      usage?: {
        model?: string;
        modelRouting?: string;
        inputTokens?: number;
        cachedInputTokens?: number;
        outputTokens?: number;
        costUsd?: number;
      };
      extensions?: Record<string, unknown>;
    }
  | {
      specVersion?: "1.0";
      id?: string;
      source?: string;
      type?: string;
      time?: string;
      subject?: string;
      schema?: string;
      contentType?: string;
      trace?: { traceparent?: string; tracestate?: string };
      run?: { sessionId?: string; runId?: string };
      kind: "input.requested";
      work: {
        id: string;
        title?: string;
        summary?: string;
        reason?: string;
        progress?: number;
        status?: "running" | "waiting" | "blocked" | "failed" | "completed" | "cancelled";
      };
      interaction: { id: string };
      request:
        | { kind: "approval"; title?: string; summary?: string; requireReason?: boolean }
        | {
            kind: "choice";
            title?: string;
            summary?: string;
            selectionMode: "single" | "multiple";
            allowTextResponse?: boolean;
            options: Array<{ id: string; label: string; summary?: string }>;
          }
        | {
            kind: "form";
            title?: string;
            summary?: string;
            fields: Array<{
              id: string;
              label: string;
              type: "text" | "textarea" | "number" | "select" | "boolean";
              required?: boolean;
              options?: Array<{ value: string; label: string }>;
            }>;
          };
      actor?: {
        id: string;
        kind?: "agent" | "subagent" | "host" | "system" | "human";
        label?: string;
      };
      facts?: { capabilityFamily?: string; activityCategory?: string };
      hints?: {
        consequence?: "low" | "medium" | "high";
        capabilityFamily?: string;
        activityCategory?: string;
        requestKind?: "approval" | "choice" | "form";
      };
      context?: { items?: Array<{ id: string; label?: string; value: string | number | boolean }> };
      automation?: {
        runMode?: "interactive" | "background" | "scheduled";
        trigger?: string;
        recurrence?: "once" | "recurring";
        scheduleId?: string;
      };
      execution?: { surface?: string; placement?: string; runner?: string; environment?: string };
      governance?: {
        policyId?: string;
        approvalState?: "not_required" | "pending" | "approved" | "rejected";
        approvalId?: string;
        decisionId?: string;
      };
      usage?: {
        model?: string;
        modelRouting?: string;
        inputTokens?: number;
        cachedInputTokens?: number;
        outputTokens?: number;
        costUsd?: number;
      };
      extensions?: Record<string, unknown>;
    };
export type WorkEventBatch = WorkEvent[];
export type WorkEventKind = WorkEvent["kind"];
export type WorkStatus = "running" | "waiting" | "blocked" | "failed" | "completed" | "cancelled";
export type WorkRequestKind = "approval" | "choice" | "form";
export type WorkEventContextItem = { id: string; label?: string; value: string | number | boolean };
export type WorkEventRequest =
  | { kind: "approval"; title?: string; summary?: string; requireReason?: boolean }
  | {
      kind: "choice";
      title?: string;
      summary?: string;
      selectionMode: "single" | "multiple";
      allowTextResponse?: boolean;
      options: Array<{ id: string; label: string; summary?: string }>;
    }
  | {
      kind: "form";
      title?: string;
      summary?: string;
      fields: Array<{
        id: string;
        label: string;
        type: "text" | "textarea" | "number" | "select" | "boolean";
        required?: boolean;
        options?: Array<{ value: string; label: string }>;
      }>;
    };

export type WorkReceipt = {
  ok: true;
  apiVersion: "1.0";
  accepted: number;
  receivedAs: "text" | "event" | "batch";
  message: string;
  published: Array<{
    taskId: string;
    type: string;
    title?: string;
    summary?: string;
    status?: string;
    interactionId?: string;
    responsePath?: string;
    responseUrl?: string;
  }>;
  retention?: { pendingTtlMs: number; terminalRetentionMs: number; capacity: number };
  next?: Array<{ when: string; send: "text" | "WorkEvent" | "WorkEvent[]"; why: string }>;
};
export type WorkReceiptItem = WorkReceipt["published"][number];
export type WorkReceiptMode = "text" | "event" | "batch";
export type WorkReceiptNextStep = NonNullable<WorkReceipt["next"]>[number];
export type WorkResponseAnswer =
  | { kind: "acknowledged" }
  | { kind: "approved"; reason?: string }
  | { kind: "rejected"; reason?: string }
  | { kind: "option_selected"; optionIds: Array<string> }
  | { kind: "text_submitted"; text: string }
  | { kind: "form_submitted"; values: Record<string, unknown> }
  | { kind: "dismissed" };
export type WorkResponse =
  | {
      ok: true;
      apiVersion: "1.0";
      taskId: string;
      interactionId: string;
      message: string;
      state: "pending";
      expiresAt: string;
    }
  | {
      ok: true;
      apiVersion: "1.0";
      taskId: string;
      interactionId: string;
      message: string;
      state: "answered";
      response:
        | { kind: "acknowledged" }
        | { kind: "approved"; reason?: string }
        | { kind: "rejected"; reason?: string }
        | { kind: "option_selected"; optionIds: Array<string> }
        | { kind: "text_submitted"; text: string }
        | { kind: "form_submitted"; values: Record<string, unknown> }
        | { kind: "dismissed" };
      answeredAt: string;
      retentionExpiresAt: string;
    }
  | {
      ok: true;
      apiVersion: "1.0";
      taskId: string;
      interactionId: string;
      message: string;
      state: "expired";
      expiresAt: string;
      retentionExpiresAt: string;
    }
  | {
      ok: true;
      apiVersion: "1.0";
      taskId: string;
      interactionId: string;
      message: string;
      state: "cancelled";
      cancelledAt: string;
      retentionExpiresAt: string;
    };
export type WorkResponseState = "pending" | "answered" | "expired" | "cancelled";
export type WorkEndpointDescription = {
  apiVersion: "1.0";
  path: "/work";
  method: "POST";
  summary: string;
  auth: string;
  send: Array<{
    receivedAs: "text" | "event" | "batch";
    contentType: string;
    body: string;
    bestFor: string;
    example: string;
  }>;
  response: {
    path: "/work/response/{interactionId}";
    deletePath: "/work/response/{interactionId}";
    bestFor: string;
    states: Array<"pending" | "answered" | "expired" | "cancelled">;
  };
  retention: { pendingTtlMs: number; terminalRetentionMs: number; capacity: number };
  next: Array<{ when: string; send: "text" | "WorkEvent" | "WorkEvent[]"; why: string }>;
};
