export const IMPORTED_SESSION_SCHEMA_VERSION = 1 as const;
export const SESSION_BUNDLE_SCHEMA_VERSION = 1 as const;
export const KERNEL_DECISION_RECORD_PROJECTION_V1_VERSION = 1 as const;
export const KERNEL_DECISION_RECORD_PROJECTION_VERSION = 2 as const;
export type KernelDecisionRecordProjectionVersion =
  | typeof KERNEL_DECISION_RECORD_PROJECTION_V1_VERSION
  | typeof KERNEL_DECISION_RECORD_PROJECTION_VERSION;

export const OFFLINE_REVIEW_ARTIFACT_SCHEMA_VERSION = 1 as const;
export const OFFLINE_REVIEW_REPORT_SCHEMA_VERSION = 1 as const;
export const OFFLINE_REVIEW_RECOMMENDATION_SCHEMA_VERSION = 1 as const;
export const OFFLINE_REVIEW_RUN_SCHEMA_VERSION = 1 as const;
export const OFFLINE_REVIEW_BATCH_REPORT_SCHEMA_VERSION = 1 as const;
export const DEFAULT_OFFLINE_REVIEW_RUBRIC_VERSION = "offline-ai-review-v1" as const;

export const AUTORESEARCH_CALIBRATION_CASE_SCHEMA_VERSION = 1 as const;
export const AUTORESEARCH_CALIBRATION_REPORT_SCHEMA_VERSION = 1 as const;
export const AUTORESEARCH_OPTIMIZATION_BRIEF_SCHEMA_VERSION = 1 as const;
export const AUTORESEARCH_PROPOSAL_RUN_SCHEMA_VERSION = 1 as const;
export const AUTORESEARCH_RUNNER_RUN_SCHEMA_VERSION = 1 as const;
export const AUTORESEARCH_OPTIMIZER_RUN_SCHEMA_VERSION = 1 as const;
export const AUTORESEARCH_FINAL_REPORT_SCHEMA_VERSION = 1 as const;
export const AUTORESEARCH_RETAINED_BACKLOG_SCHEMA_VERSION = 1 as const;
export const AUTORESEARCH_CAMPAIGN_SCHEMA_VERSION = 1 as const;
export const AUTORESEARCH_RUN_STATUS_SCHEMA_VERSION = 1 as const;
export const AUTORESEARCH_SERVICE_STATUS_SCHEMA_VERSION = 1 as const;
export const AUTORESEARCH_SWEEP_STATUS_SCHEMA_VERSION = 1 as const;
