export const KERNEL_CORPUS_SCENARIO_IDS = [
  "golden:kernel-corpus:alarmist-read-approval-stays-low-risk",
  "golden:kernel-corpus:bare-nonzero-command-exit-plans-next-without-ambiguity",
  "golden:kernel-corpus:command-owned-technical-observation-stays-medium",
  "golden:kernel-corpus:command-test-progress-observation-stays-medium",
  "golden:kernel-corpus:conflicting-relation-targets-queue-behind-current",
  "golden:kernel-corpus:delayed-lifecycle-events-preserve-fresh-recurrence",
  "golden:kernel-corpus:duplicate-relation-hints-collapse-to-targeted-evidence",
  "golden:kernel-corpus:empty-failure-payload-stays-visible-with-weak-evidence",
  "golden:kernel-corpus:failed-status-file-operation-success-stays-ambient",
  "golden:kernel-corpus:failed-status-mixed-procedural-failure-stays-visible",
  "golden:kernel-corpus:failed-status-procedural-observation-stays-ambient",
  "golden:kernel-corpus:failed-status-routine-observation-stays-ambient",
  "golden:kernel-corpus:failed-status-yamllint-warning-observation-preserves-high",
  "golden:kernel-corpus:forged-observation-hint-keeps-failed-routing",
  "golden:kernel-corpus:hinted-or-forged-outcome-only-softening-is-rejected",
  "golden:kernel-corpus:interleaved-supersede-with-background-noise",
  "golden:kernel-corpus:known-command-operation-success-text-stays-failure",
  "golden:kernel-corpus:metadata-heavy-status-noise-stays-ambient",
  "golden:kernel-corpus:observational-status-conflict-preserves-high",
  "golden:kernel-corpus:prospective-resolution-verification-preserves-focus",
  "golden:kernel-corpus:read-owned-arrow-terminal-diagnostic-stays-failure",
  "golden:kernel-corpus:read-owned-clipped-arrow-window-preserves-high",
  "golden:kernel-corpus:read-owned-flattened-source-preserves-high",
  "golden:kernel-corpus:read-truncation-protocol-stays-ambient",
  "golden:kernel-corpus:repeated-failure-refreshes-current-episode",
  "golden:kernel-corpus:repeated-low-confidence-failures-stay-queued",
  "golden:kernel-corpus:repeated-status-delivery-stays-one-ambient-frame",
  "golden:kernel-corpus:resolution-after-active-failure-clears-focus",
  "golden:kernel-corpus:running-blocked-wording-activates-empty-slot",
  "golden:kernel-corpus:source-risk-outranks-low-confidence-hint",
  "golden:kernel-corpus:source-shaped-runtime-terminal-stays-failure",
  "golden:kernel-corpus:structured-outcome-only-command-exit-plans-next-without-ambiguity",
  "golden:kernel-corpus:superseding-approval-clears-obsolete-queued-step",
  "golden:kernel-corpus:truncated-outcome-only-exit-stays-high",
  "golden:kernel-corpus:waiting-wording-blocked-under-absence",
] as const;

export { KERNEL_CORPUS_COVERAGE_DIMENSIONS } from "./kernel-corpus-profile-dimensions.js";
