export const KERNEL_CORPUS_COVERAGE_DIMENSIONS = [
  {
    id: "source_fact_authority",
    scenarioIds: [
      "golden:kernel-corpus:alarmist-read-approval-stays-low-risk",
      "golden:kernel-corpus:bash-compiler-source-diagnostic-stays-terminal",
      "golden:kernel-corpus:bash-loader-path-heavy-diagnostic-stays-terminal",
      "golden:kernel-corpus:bash-loader-plain-diagnostic-stays-terminal",
      "golden:kernel-corpus:bare-nonzero-command-exit-plans-next-without-ambiguity",
      "golden:kernel-corpus:completed-update-session-activity-preserves-source",
      "golden:kernel-corpus:empty-failure-payload-stays-visible-with-weak-evidence",
      "golden:kernel-corpus:failed-read-observation-stays-medium-ambient",
      "golden:kernel-corpus:forged-observation-hint-keeps-failed-routing",
      "golden:kernel-corpus:failed-status-mixed-procedural-failure-stays-visible",
      "golden:kernel-corpus:hinted-or-forged-outcome-only-softening-is-rejected",
      "golden:kernel-corpus:known-command-operation-success-text-stays-failure",
      "golden:kernel-corpus:read-owned-arrow-terminal-diagnostic-stays-failure",
      "golden:kernel-corpus:read-owned-clipped-arrow-window-preserves-high",
      "golden:kernel-corpus:read-owned-flattened-source-preserves-high",
      "golden:kernel-corpus:read-owned-midfile-source-preserves-high",
      "golden:kernel-corpus:read-source-window-limit-stays-visible",
      "golden:kernel-corpus:source-shaped-runtime-terminal-stays-failure",
      "golden:kernel-corpus:source-risk-outranks-low-confidence-hint",
      "golden:kernel-corpus:structured-outcome-only-command-exit-plans-next-without-ambiguity",
      "golden:kernel-corpus:truncated-outcome-only-exit-stays-high",
    ],
  },
  {
    id: "relation_target_conflict",
    scenarioIds: ["golden:kernel-corpus:conflicting-relation-targets-queue-behind-current"],
  },
  {
    id: "relation_hint_canonicalization",
    scenarioIds: ["golden:kernel-corpus:duplicate-relation-hints-collapse-to-targeted-evidence"],
  },
  {
    id: "status_noise",
    scenarioIds: [
      "golden:kernel-corpus:bash-compiler-source-diagnostic-stays-terminal",
      "golden:kernel-corpus:bash-loader-path-heavy-diagnostic-stays-terminal",
      "golden:kernel-corpus:bash-loader-plain-diagnostic-stays-terminal",
      "golden:kernel-corpus:command-owned-technical-observation-stays-medium",
      "golden:kernel-corpus:command-test-progress-observation-stays-medium",
      "golden:kernel-corpus:completed-update-implied-ask-stays-status-shaped",
      "golden:kernel-corpus:completed-update-session-activity-preserves-source",
      "golden:kernel-corpus:bare-nonzero-command-exit-plans-next-without-ambiguity",
      "golden:kernel-corpus:empty-failure-payload-stays-visible-with-weak-evidence",
      "golden:kernel-corpus:failed-status-file-operation-success-stays-ambient",
      "golden:kernel-corpus:failed-status-mixed-procedural-failure-stays-visible",
      "golden:kernel-corpus:failed-status-procedural-observation-stays-ambient",
      "golden:kernel-corpus:failed-status-routine-observation-stays-ambient",
      "golden:kernel-corpus:failed-status-yamllint-warning-observation-preserves-high",
      "golden:kernel-corpus:forged-observation-hint-keeps-failed-routing",
      "golden:kernel-corpus:hinted-or-forged-outcome-only-softening-is-rejected",
      "golden:kernel-corpus:metadata-heavy-status-noise-stays-ambient",
      "golden:kernel-corpus:known-command-operation-success-text-stays-failure",
      "golden:kernel-corpus:observational-status-conflict-preserves-high",
      "golden:kernel-corpus:operational-progress-stays-medium-ambient",
      "golden:kernel-corpus:interleaved-supersede-with-background-noise",
      "golden:kernel-corpus:read-lifecycle-progress-stays-ambient",
      "golden:kernel-corpus:read-owned-clipped-arrow-window-preserves-high",
      "golden:kernel-corpus:read-owned-flattened-source-preserves-high",
      "golden:kernel-corpus:read-owned-markdown-manual-stays-ambient",
      "golden:kernel-corpus:read-owned-midfile-source-preserves-high",
      "golden:kernel-corpus:read-source-window-limit-stays-visible",
      "golden:kernel-corpus:read-truncation-protocol-stays-ambient",
      "golden:kernel-corpus:source-shaped-runtime-terminal-stays-failure",
      "golden:kernel-corpus:structured-outcome-only-command-exit-plans-next-without-ambiguity",
      "golden:kernel-corpus:truncated-outcome-only-exit-stays-high",
      "golden:kernel-corpus:repeated-status-delivery-stays-one-ambient-frame",
      "golden:kernel-corpus:duplicate-running-progress-suppresses-stale-repeat",
    ],
  },
  {
    id: "observational_status_conflict",
    scenarioIds: [
      "golden:kernel-corpus:command-owned-technical-observation-stays-medium",
      "golden:kernel-corpus:command-test-progress-observation-stays-medium",
      "golden:kernel-corpus:failed-read-observation-stays-medium-ambient",
      "golden:kernel-corpus:failed-status-file-operation-success-stays-ambient",
      "golden:kernel-corpus:failed-status-procedural-observation-stays-ambient",
      "golden:kernel-corpus:failed-status-routine-observation-stays-ambient",
      "golden:kernel-corpus:failed-status-yamllint-warning-observation-preserves-high",
      "golden:kernel-corpus:forged-observation-hint-keeps-failed-routing",
      "golden:kernel-corpus:observational-status-conflict-preserves-high",
      "golden:kernel-corpus:read-owned-clipped-arrow-window-preserves-high",
      "golden:kernel-corpus:read-owned-flattened-source-preserves-high",
      "golden:kernel-corpus:read-owned-markdown-manual-stays-ambient",
      "golden:kernel-corpus:read-owned-midfile-source-preserves-high",
      "golden:kernel-corpus:read-truncation-protocol-stays-ambient",
    ],
  },
  {
    id: "interleaved_lifecycle",
    scenarioIds: ["golden:kernel-corpus:interleaved-supersede-with-background-noise"],
  },
  {
    id: "completed_update_semantics",
    scenarioIds: [
      "golden:kernel-corpus:completed-update-blocker-stays-status-shaped",
      "golden:kernel-corpus:completed-update-implied-ask-stays-status-shaped",
      "golden:kernel-corpus:completed-update-session-activity-preserves-source",
      "golden:kernel-corpus:delayed-lifecycle-events-preserve-fresh-recurrence",
      "golden:kernel-corpus:repeated-low-confidence-failures-stay-queued",
      "golden:kernel-corpus:resolution-after-active-failure-clears-focus",
    ],
  },
  {
    id: "low_confidence_failure_pressure",
    scenarioIds: ["golden:kernel-corpus:repeated-low-confidence-failures-stay-queued"],
  },
  {
    id: "source_quality_gap",
    scenarioIds: [
      "golden:kernel-corpus:empty-failure-payload-stays-visible-with-weak-evidence",
      "golden:kernel-corpus:read-source-window-limit-stays-visible",
    ],
  },
  {
    id: "repeated_failure_lifecycle",
    scenarioIds: ["golden:kernel-corpus:repeated-failure-refreshes-current-episode"],
  },
  {
    id: "superseded_queue_cleanup",
    scenarioIds: ["golden:kernel-corpus:superseding-approval-clears-obsolete-queued-step"],
  },
  {
    id: "episode_resolution",
    scenarioIds: [
      "golden:kernel-corpus:prospective-resolution-verification-preserves-focus",
      "golden:kernel-corpus:resolution-after-active-failure-clears-focus",
    ],
  },
  {
    id: "event_time_lifecycle",
    scenarioIds: [
      "golden:kernel-corpus:delayed-lifecycle-events-preserve-fresh-recurrence",
      "golden:kernel-corpus:duplicate-running-progress-suppresses-stale-repeat",
      "golden:kernel-corpus:read-lifecycle-progress-stays-ambient",
    ],
  },
  {
    id: "operator_absence",
    scenarioIds: ["golden:kernel-corpus:waiting-wording-blocked-under-absence"],
  },
  {
    id: "semantic_blocking_empty_slot",
    scenarioIds: [
      "golden:kernel-corpus:completed-update-blocker-stays-status-shaped",
      "golden:kernel-corpus:running-blocked-wording-activates-empty-slot",
    ],
  },
  {
    id: "ambient_progress_shapes",
    scenarioIds: [
      "golden:kernel-corpus:duplicate-running-progress-suppresses-stale-repeat",
      "golden:kernel-corpus:failed-read-observation-stays-medium-ambient",
      "golden:kernel-corpus:operational-progress-stays-medium-ambient",
      "golden:kernel-corpus:read-lifecycle-progress-stays-ambient",
    ],
  },
] as const;
